let token=localStorage.getItem("nexora_admin"),site=null;const $=id=>document.getElementById(id);
async function api(url,opt={}){opt.headers={...(opt.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opt),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({password:$("password").value})});token=d.token;localStorage.setItem("nexora_admin",token);show()}catch(x){$("loginMsg").textContent=x.message}};
function show(){$("login").hidden=true;$("app").hidden=false;load()}
async function load(){try{site=await api("/api/site");render()}catch(e){localStorage.removeItem("nexora_admin");location.reload()}}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){const s=site.settings||{},h=site.hero||{};$("brand").value=s.brand||"";$("tagline").value=s.tagline||"";$("email").value=s.email||"";$("whatsapp").value=s.whatsapp||"";$("eyebrow").value=h.eyebrow||"";$("heroTitle").value=h.title||"";$("heroDescription").value=h.description||"";$("leadCount").textContent=(site.leads||[]).length;renderServices();renderLeads()}
function renderServices(){const b=$("serviceList");b.innerHTML="";(site.services||[]).forEach((x,i)=>{const d=document.createElement("div");d.className="service";d.innerHTML='<input><textarea></textarea><button>Delete</button>';d.querySelector("input").value=x.title;d.querySelector("textarea").value=x.description;d.querySelector("button").onclick=()=>{site.services.splice(i,1);renderServices()};d.querySelector("input").oninput=e=>site.services[i].title=e.target.value;d.querySelector("textarea").oninput=e=>site.services[i].description=e.target.value;b.appendChild(d)})}
function renderLeads(){$("leadsList").innerHTML=(site.leads||[]).map(x=>'<div class="lead"><b>'+esc(x.name)+' · '+esc(x.email)+'</b><small>'+esc(x.status)+' · '+new Date(x.createdAt).toLocaleString()+'</small><p>'+esc(x.message)+'</p></div>').join("")||"<p>No leads yet.</p>"}
document.querySelectorAll("aside button[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".panel").forEach(p=>p.hidden=true);$(b.dataset.tab).hidden=false;$("title").textContent=b.textContent});
$("addService").onclick=()=>{site.services.push({title:"New service",description:"Describe this service."});renderServices()};
$("save").onclick=async()=>{site.settings.brand=$("brand").value;site.settings.tagline=$("tagline").value;site.settings.email=$("email").value;site.settings.whatsapp=$("whatsapp").value;site.hero.eyebrow=$("eyebrow").value;site.hero.title=$("heroTitle").value;site.hero.description=$("heroDescription").value;try{site=await api("/api/site",{method:"PUT",body:JSON.stringify(site)});alert("Saved successfully");render()}catch(e){alert(e.message)}};
$("logout").onclick=async()=>{try{await api("/api/logout",{method:"POST"})}finally{localStorage.removeItem("nexora_admin");location.reload()}};if(token)show();