let token=localStorage.getItem("nfx_admin"),site=null;const $=id=>document.getElementById(id);
async function api(u,o={}){o.headers={...(o.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});token=d.token;localStorage.setItem("nfx_admin",token);show()}catch(x){$("loginMsg").textContent=x.message}};
function show(){$("login").hidden=true;$("app").hidden=false;load()}
async function load(){try{site=await api("/api/site");render()}catch(e){localStorage.removeItem("nfx_admin");location.reload()}}
function render(){const s=site.settings,h=site.hero,c=site.chatbot; $("brand").value=s.brand||"";$("announcement").value=s.announcement||"";$("heroEyebrow").value=h.eyebrow||"";$("heroTitle").value=h.title||"";$("heroDesc").value=h.description||"";$("heroImage").value=h.image||"";$("aboutTitle").value=s.aboutTitle||"";$("aboutText").value=s.aboutText||"";$("storeEmail").value=s.email||"";$("storeWhatsapp").value=s.whatsapp||"";$("storePhone").value=s.phone||"";$("benefits").value=(site.benefits||[]).join("\n");$("botName").value=c.name||"";$("botWelcome").value=c.welcome||"";$("botKnowledge").value=c.knowledge||"";$("botQuick").value=(c.quickReplies||[]).join("\n");$("socialWhatsapp").value=site.socials.whatsapp||"";$("socialFacebook").value=site.socials.facebook||"";$("socialInstagram").value=site.socials.instagram||"";$("socialTiktok").value=site.socials.tiktok||"";renderProducts();renderOrders();renderReviews();renderAgents();renderLeads();stats()}
async function stats(){try{const s=await api("/api/admin/stats");$("stProducts").textContent=s.products;$("stOrders").textContent=s.orders;$("stPending").textContent=s.pendingOrders;$("stRevenue").textContent="৳"+Number(s.revenue).toLocaleString("en-BD");$("stReviews").textContent=s.reviews;$("stLeads").textContent=s.leads}catch(e){}}
function renderProducts(){const b=$("productList");b.innerHTML="";(site.products||[]).forEach((p,i)=>{const d=document.createElement("div");d.className="product-admin";d.innerHTML='<img><div><input class="pn"><input class="pc"><input class="pp"><input class="po"><input class="pi"><textarea class="pd"></textarea><input class="ps" placeholder="Sizes comma separated"></div><button class="danger">Delete</button>';d.querySelector("img").src=p.image;d.querySelector(".pn").value=p.name;d.querySelector(".pc").value=p.category;d.querySelector(".pp").value=p.price;d.querySelector(".po").value=p.oldPrice||"";d.querySelector(".pi").value=p.image;d.querySelector(".pd").value=p.description;d.querySelector(".ps").value=(p.sizes||[]).join(", ");["pn","pc","pp","po","pi","pd","ps"].forEach((c,j)=>d.querySelector("."+c).oninput=e=>{const v=e.target.value;if(c==="pp"||c==="po")p[c==="pp"?"price":"oldPrice"]=Number(v)||0;else if(c==="ps")p.sizes=v.split(",").map(x=>x.trim()).filter(Boolean);else p[{pn:"name",pc:"category",pi:"image",pd:"description"}[c]]=v;if(c==="pi")d.querySelector("img").src=v});d.querySelector("button").onclick=()=>{site.products.splice(i,1);renderProducts()};b.appendChild(d)})}
$("addProduct").onclick=()=>{site.products.push({id:"NF-"+Date.now(),name:"New Fashion Product",category:"Women",price:0,oldPrice:0,image:"",description:"Product description",sizes:["S","M","L"]});renderProducts()};
async function renderOrders(){const list=await api("/api/admin/orders"),b=$("ordersList");b.innerHTML="";list.slice().reverse().forEach(o=>{const d=document.createElement("div");d.className="order-admin";d.innerHTML='<b></b><span class="tag"></span><small></small><p></p><select class="order-status"><option>pending</option><option>confirmed</option><option>cancelled</option><option>shipped</option><option>delivered</option></select><button class="approve">Update</button>';d.querySelector("b").textContent=o.id+" · "+o.name+" · "+o.phone;d.querySelector(".tag").textContent="৳"+o.total;d.querySelector("small").textContent=new Date(o.createdAt).toLocaleString();d.querySelector("p").textContent=o.items.map(i=>i.name+" × "+i.quantity+" ("+i.size+")").join(" | ")+" · "+o.address;d.querySelector("select").value=o.status;d.querySelector("button").onclick=async()=>{await api("/api/admin/orders/"+o.id,{method:"PATCH",body:JSON.stringify({status:d.querySelector("select").value})});renderOrders();stats()};b.appendChild(d)})}
async function renderReviews(){const list=await api("/api/admin/reviews"),b=$("reviewsList");b.innerHTML="";list.slice().reverse().forEach(r=>{const d=document.createElement("div");d.className="review-admin";d.innerHTML='<b></b><small></small><p></p><button class="approve">Approve</button><button class="hide">Reject / Hide</button>';d.querySelector("b").textContent="★".repeat(r.rating)+" · "+r.name;d.querySelector("small").textContent=r.status+" · "+new Date(r.createdAt).toLocaleString();d.querySelector("p").textContent=r.text;d.querySelector(".approve").onclick=()=>review(r.id,"approved");d.querySelector(".hide").onclick=()=>review(r.id,"rejected");b.appendChild(d)})}
async function review(id,status){await api("/api/admin/reviews/"+id,{method:"PATCH",body:JSON.stringify({status})});renderReviews();stats()}
function renderAgents(){const b=$("agentList");b.innerHTML="";(site.agents||[]).forEach((a,i)=>{const d=document.createElement("div");d.className="agent-admin";d.innerHTML='<input class="an"><input class="ap"><input class="aw"><button class="danger">Delete</button>';d.querySelector(".an").value=a.name;d.querySelector(".ap").value=a.phone;d.querySelector(".aw").value=a.whatsapp;d.querySelector(".an").oninput=e=>a.name=e.target.value;d.querySelector(".ap").oninput=e=>a.phone=e.target.value;d.querySelector(".aw").oninput=e=>a.whatsapp=e.target.value;d.querySelector("button").onclick=()=>{site.agents.splice(i,1);renderAgents()};b.appendChild(d)})}
$("addAgent").onclick=()=>{site.agents.push({id:"a"+Date.now(),name:"Fashion Agent",phone:"",whatsapp:"",active:true});renderAgents()};
function renderLeads(){api("/api/admin/leads").then(list=>{$("leadsList").innerHTML="";list.slice().reverse().forEach(x=>{const d=document.createElement("div");d.className="lead-admin";d.innerHTML="<b></b><small></small><p></p>";d.querySelector("b").textContent=x.name+" · "+x.phone;d.querySelector("small").textContent=x.status+" · "+new Date(x.createdAt).toLocaleString();d.querySelector("p").textContent=(x.message||"")+" "+(x.email||"");$("leadsList").appendChild(d)})})}
document.querySelectorAll("aside button[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".panel").forEach(p=>p.hidden=true);$(b.dataset.tab).hidden=false;$("pageTitle").textContent=b.textContent});
$("save").onclick=async()=>{const s=site.settings,h=site.hero,c=site.chatbot;s.brand=$("brand").value;s.announcement=$("announcement").value;h.eyebrow=$("heroEyebrow").value;h.title=$("heroTitle").value;h.description=$("heroDesc").value;h.image=$("heroImage").value;s.aboutTitle=$("aboutTitle").value;s.aboutText=$("aboutText").value;s.email=$("storeEmail").value;s.whatsapp=$("storeWhatsapp").value;s.phone=$("storePhone").value;site.benefits=$("benefits").value.split("\n").map(x=>x.trim()).filter(Boolean);c.name=$("botName").value;c.welcome=$("botWelcome").value;c.knowledge=$("botKnowledge").value;c.quickReplies=$("botQuick").value.split("\n").map(x=>x.trim()).filter(Boolean);site.socials.whatsapp=$("socialWhatsapp").value;site.socials.facebook=$("socialFacebook").value;site.socials.instagram=$("socialInstagram").value;site.socials.tiktok=$("socialTiktok").value;try{site=await api("/api/site",{method:"PUT",body:JSON.stringify(site)});alert("All changes saved.");render()}catch(e){alert(e.message)}};
$("logout").onclick=async()=>{try{await api("/api/logout",{method:"POST"})}finally{localStorage.removeItem("nfx_admin");location.reload()}};if(token)show();