let token=localStorage.getItem("nfx_admin"),site=null;const $=id=>document.getElementById(id);
async function api(u,o={}){o.headers={...(o.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
function show(){$("login").hidden=true;$("app").hidden=false;load()}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});token=d.token;localStorage.setItem("nfx_admin",token);show()}catch(x){$("loginMsg").textContent=x.message}}
async function load(){try{site=await api("/api/site");normalize();renderAll()}catch(e){localStorage.removeItem("nfx_admin");location.reload()}}
function normalize(){site.settings=site.settings||{};site.hero=site.hero||{};site.chatbot=site.chatbot||{};site.socials=site.socials||{};site.theme=site.theme||{bg:"#f7f6f2",panel:"#fff",ink:"#151515",muted:"#77736c",accent:"#b99555",radius:"14px"};site.navigation=site.navigation||[];site.sections=site.sections||[];site.seo=site.seo||{};site.footer=site.footer||{};site.media=site.media||[];site.products=site.products||[];site.reviews=site.reviews||[];site.agents=site.agents||[]}
function val(id,v){if($(id))$(id).value=v??""}
function renderAll(){const s=site.settings,h=site.hero,c=site.chatbot,t=site.theme,seo=site.seo;val("brand",s.brand);val("announcement",s.announcement);val("tagline",s.tagline);val("favicon",s.favicon);val("heroEyebrow",h.eyebrow);val("heroTitle",h.title);val("heroDesc",h.description);val("heroImage",h.image);val("aboutTitle",s.aboutTitle);val("aboutText",s.aboutText);val("storeEmail",s.email);val("storeWhatsapp",s.whatsapp);val("storePhone",s.phone);val("benefits",(site.benefits||[]).join("\n"));val("botName",c.name);val("botWelcome",c.welcome);val("botKnowledge",c.knowledge);val("botQuick",(c.quickReplies||[]).join("\n"));val("socialWhatsapp",site.socials.whatsapp);val("socialFacebook",site.socials.facebook);val("socialInstagram",site.socials.instagram);val("socialTiktok",site.socials.tiktok);val("themeBg",t.bg);val("themePanel",t.panel);val("themeInk",t.ink);val("themeMuted",t.muted);val("themeAccent",t.accent);val("themeRadius",t.radius);val("seoTitle",seo.title);val("seoDescription",seo.description);val("seoImage",seo.ogImage);val("canonical",seo.canonical);val("robots",seo.robots);val("footerAboutEdit",site.footer.about);val("footerMadeBy",site.footer.madeBy||"Nexora WEB");val("footerCopyright",site.footer.copyright||"© 2026");renderSections();renderNavigation();renderProducts();renderAgents();renderMedia();renderReviews();renderOrders();renderLeads();stats()}
async function stats(){try{const s=await api("/api/admin/stats");val("stProducts",s.products);val("stOrders",s.orders);val("stPending",s.pendingOrders);val("stRevenue","৳"+Number(s.revenue).toLocaleString("en-BD"));val("stReviews",s.reviews);val("stLeads",s.leads)}catch{}}
function renderSections(){const b=$("sectionList");b.innerHTML="";site.sections.forEach((s,i)=>{const d=document.createElement("div");d.className="builder-item";d.draggable=true;d.innerHTML='<div class="drag">☷</div><div class="builder-fields"><input class="se-title" placeholder="Section title"><input class="se-eye" placeholder="Eyebrow"><select class="se-type"><option value="text">Text / Content</option><option value="image-text">Image + Text</option><option value="cta">CTA</option><option value="products">Products</option><option value="categories">Categories</option><option value="about">About</option><option value="reviews">Reviews</option><option value="contact">Contact</option></select><textarea class="se-text" placeholder="Section content"></textarea><input class="se-image" placeholder="Image URL"><input class="se-button" placeholder="Button text"><input class="se-link" placeholder="Button link"></div><label class="switch">Show <input class="se-visible" type="checkbox"></label><button class="danger se-delete">Delete</button>';valEl(d,"se-title",s.title);valEl(d,"se-eye",s.eyebrow);d.querySelector(".se-type").value=s.type||"text";valEl(d,"se-text",s.text);valEl(d,"se-image",s.image);valEl(d,"se-button",s.button);valEl(d,"se-link",s.buttonLink);d.querySelector(".se-visible").checked=s.visible!==false;const update=()=>{s.title=d.querySelector(".se-title").value;s.eyebrow=d.querySelector(".se-eye").value;s.type=d.querySelector(".se-type").value;s.text=d.querySelector(".se-text").value;s.image=d.querySelector(".se-image").value;s.button=d.querySelector(".se-button").value;s.buttonLink=d.querySelector(".se-link").value;s.visible=d.querySelector(".se-visible").checked};d.querySelectorAll("input,textarea,select").forEach(x=>x.oninput=update);d.querySelector(".se-delete").onclick=()=>{site.sections.splice(i,1);renderSections()};d.ondragstart=e=>e.dataTransfer.setData("text/plain",i);d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("text/plain"));const [m]=site.sections.splice(from,1);site.sections.splice(i,0,m);renderSections()};b.appendChild(d)})}
function valEl(d,c,v){const x=d.querySelector("."+c);if(x)x.value=v??""}
$("addSection").onclick=()=>{site.sections.push({id:"cms-"+Date.now(),type:$("sectionType").value,title:"New section",eyebrow:"CUSTOM SECTION",text:"Write your content here.",visible:true});renderSections()}
function renderNavigation(){const b=$("navList");b.innerHTML="";site.navigation.forEach((n,i)=>{const d=document.createElement("div");d.className="builder-item nav-item";d.innerHTML='<div class="builder-fields"><input class="nl"><input class="nh"><label class="switch">Show <input class="nv" type="checkbox"></label></div><button class="danger">Delete</button>';valEl(d,"nl",n.label);valEl(d,"nh",n.href);d.querySelector(".nv").checked=n.visible!==false;d.querySelector(".nl").oninput=e=>n.label=e.target.value;d.querySelector(".nh").oninput=e=>n.href=e.target.value;d.querySelector(".nv").onchange=e=>n.visible=e.target.checked;d.querySelector(".danger").onclick=()=>{site.navigation.splice(i,1);renderNavigation()};b.appendChild(d)})}
$("addNav").onclick=()=>{site.navigation.push({label:"New link",href:"#",visible:true});renderNavigation()}
function renderProducts(){const b=$("productList");b.innerHTML="";site.products.forEach((p,i)=>{const d=document.createElement("div");d.className="product-admin";d.innerHTML='<img><div class="builder-fields"><input class="pn"><input class="pc"><input class="pp" type="number"><input class="po" type="number"><input class="pi"><textarea class="pd"></textarea><input class="ps" placeholder="Sizes comma separated"><input class="pb" placeholder="Badge"></div><button class="danger">Delete</button>';d.querySelector("img").src=p.image||"";valEl(d,"pn",p.name);valEl(d,"pc",p.category);valEl(d,"pp",p.price);valEl(d,"po",p.oldPrice);valEl(d,"pi",p.image);valEl(d,"pd",p.description);valEl(d,"ps",(p.sizes||[]).join(", "));valEl(d,"pb",p.badge);const map={pn:"name",pc:"category",pp:"price",po:"oldPrice",pi:"image",pd:"description",pb:"badge"};Object.entries(map).forEach(([cl,key])=>d.querySelector("."+cl).oninput=e=>{p[key]=key==="price"||key==="oldPrice"?Number(e.target.value)||0:e.target.value;if(key==="image")d.querySelector("img").src=p.image});d.querySelector(".ps").oninput=e=>p.sizes=e.target.value.split(",").map(x=>x.trim()).filter(Boolean);d.querySelector("button").onclick=()=>{site.products.splice(i,1);renderProducts()};b.appendChild(d)})}
$("addProduct").onclick=()=>{site.products.push({id:"NF-"+Date.now(),name:"New Product",category:"Women",price:0,oldPrice:0,image:"",description:"",sizes:["S","M","L"],badge:"NEW"});renderProducts()}
async function renderReviews(){const list=await api("/api/admin/reviews"),b=$("reviewsList");b.innerHTML="";list.slice().reverse().forEach(r=>{const d=document.createElement("div");d.className="review-admin";d.innerHTML='<b></b><small></small><p></p><button class="approve">Approve</button><button class="hide">Reject / Hide</button>';d.querySelector("b").textContent="★".repeat(r.rating)+" · "+r.name;d.querySelector("small").textContent=r.status;d.querySelector("p").textContent=r.text;d.querySelector(".approve").onclick=()=>review(r.id,"approved");d.querySelector(".hide").onclick=()=>review(r.id,"rejected");b.appendChild(d)})}
async function review(id,status){await api("/api/admin/reviews/"+id,{method:"PATCH",body:JSON.stringify({status})});renderReviews();stats()}
$("adminReviewForm").onsubmit=async e=>{e.preventDefault();try{const r=await api("/api/admin/reviews",{method:"POST",body:JSON.stringify({name:$("reviewName").value,rating:$("reviewRating").value,text:$("reviewText").value,featured:true})});$("adminReviewMsg").textContent="Added: "+r.review.name;e.target.reset();renderReviews();stats()}catch(x){$("adminReviewMsg").textContent=x.message}}
async function renderOrders(){const list=await api("/api/admin/orders"),b=$("ordersList");b.innerHTML="";list.slice().reverse().forEach(o=>{const d=document.createElement("div");d.className="order-admin";d.innerHTML='<b></b><span class="tag"></span><small></small><p></p><select class="order-status"><option>pending</option><option>confirmed</option><option>cancelled</option><option>shipped</option><option>delivered</option></select><button class="approve">Update</button>';d.querySelector("b").textContent=o.id+" · "+o.name+" · "+o.phone;d.querySelector(".tag").textContent="৳"+o.total;d.querySelector("small").textContent=new Date(o.createdAt).toLocaleString();d.querySelector("p").textContent=o.items.map(i=>i.name+" × "+i.quantity+" ("+i.size+")").join(" | ")+" · "+o.address;d.querySelector("select").value=o.status;d.querySelector("button").onclick=async()=>{await api("/api/admin/orders/"+o.id,{method:"PATCH",body:JSON.stringify({status:d.querySelector("select").value})});renderOrders();stats()};b.appendChild(d)})}
function renderAgents(){const b=$("agentList");b.innerHTML="";site.agents.forEach((a,i)=>{const d=document.createElement("div");d.className="agent-admin";d.innerHTML='<input class="an"><input class="ap"><input class="aw"><button class="danger">Delete</button>';valEl(d,"an",a.name);valEl(d,"ap",a.phone);valEl(d,"aw",a.whatsapp);d.querySelector(".an").oninput=e=>a.name=e.target.value;d.querySelector(".ap").oninput=e=>a.phone=e.target.value;d.querySelector(".aw").oninput=e=>a.whatsapp=e.target.value;d.querySelector("button").onclick=()=>{site.agents.splice(i,1);renderAgents()};b.appendChild(d)})}
$("addAgent").onclick=()=>{site.agents.push({id:"a"+Date.now(),name:"New agent",phone:"",whatsapp:"",active:true});renderAgents()}
function renderMedia(){const b=$("mediaList");b.innerHTML="";site.media.forEach((m,i)=>{const d=document.createElement("div");d.className="media-item";d.innerHTML='<b></b><input readonly><button class="danger">Delete</button>';d.querySelector("b").textContent=m.name;d.querySelector("input").value=m.url;d.querySelector("button").onclick=()=>{site.media.splice(i,1);renderMedia()};b.appendChild(d)})}
$("mediaForm").onsubmit=e=>{e.preventDefault();site.media.push({id:"m"+Date.now(),name:$("mediaName").value,url:$("mediaUrl").value});e.target.reset();renderMedia()}
function renderLeads(){api("/api/admin/leads").then(list=>{$("leadsList").innerHTML=list.slice().reverse().map(x=>'<div class="lead-admin"><b>'+esc(x.name)+' · '+esc(x.phone)+'</b><small>'+esc(x.status)+'</small><p>'+esc(x.message||"")+'</p></div>').join("")})}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function collect(){const s=site.settings,h=site.hero,c=site.chatbot,t=site.theme,seo=site.seo;s.brand=$("brand").value;s.announcement=$("announcement").value;s.tagline=$("tagline").value;s.favicon=$("favicon").value;h.eyebrow=$("heroEyebrow").value;h.title=$("heroTitle").value;h.description=$("heroDesc").value;h.image=$("heroImage").value;s.aboutTitle=$("aboutTitle").value;s.aboutText=$("aboutText").value;s.email=$("storeEmail").value;s.whatsapp=$("storeWhatsapp").value;s.phone=$("storePhone").value;site.benefits=$("benefits").value.split("\n").map(x=>x.trim()).filter(Boolean);c.name=$("botName").value;c.welcome=$("botWelcome").value;c.knowledge=$("botKnowledge").value;c.quickReplies=$("botQuick").value.split("\n").map(x=>x.trim()).filter(Boolean);site.socials.whatsapp=$("socialWhatsapp").value;site.socials.facebook=$("socialFacebook").value;site.socials.instagram=$("socialInstagram").value;site.socials.tiktok=$("socialTiktok").value;Object.assign(t,{bg:$("themeBg").value,panel:$("themePanel").value,ink:$("themeInk").value,muted:$("themeMuted").value,accent:$("themeAccent").value,radius:$("themeRadius").value});Object.assign(seo,{title:$("seoTitle").value,description:$("seoDescription").value,ogImage:$("seoImage").value,canonical:$("canonical").value,robots:$("robots").value});site.footer.about=$("footerAboutEdit").value;site.footer.madeBy=$("footerMadeBy").value;site.footer.copyright=$("footerCopyright").value}
$("save").onclick=async()=>{collect();try{site=await api("/api/site",{method:"PUT",body:JSON.stringify(site)});normalize();renderAll();alert("Saved & published successfully.")}catch(e){alert(e.message)}}
document.querySelectorAll("aside button[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".panel").forEach(p=>p.hidden=true);$(b.dataset.tab).hidden=false;$("pageTitle").textContent=b.textContent;document.querySelectorAll("aside button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
$("logout").onclick=async()=>{try{await api("/api/logout",{method:"POST"})}finally{localStorage.removeItem("nfx_admin");location.reload()}};if(token)show();