let site=null;const $=id=>document.getElementById(id);
async function loadSite(){try{site=await (await fetch("/api/site")).json();const s=site.settings||{},h=site.hero||{};document.title=s.brand||"NEXORA FASHION";$("brand-name").textContent=s.brand||"";$("footer-brand").textContent=s.brand||"";$("footer-tagline").textContent=s.tagline||"";$("tagline").textContent=s.tagline||"";$("hero-eyebrow").textContent=h.eyebrow||"";$("hero-title").textContent=h.title||"";$("hero-description").textContent=h.description||"";$("hero-image").src=h.image||"";renderCollections();renderReviews();setupChat()}catch(e){console.warn(e)}}
function renderCollections(){const box=$("collection-grid");box.replaceChildren(...(site.collections||[]).map((x,i)=>{const a=document.createElement("article");a.className="collection";a.innerHTML='<img loading="lazy" alt=""><div class="collection-copy"><small>0'+(i+1)+' / COLLECTION</small><h3></h3><p></p></div>';a.querySelector("img").src=x.image||"";a.querySelector("img").alt=x.name||"Fashion";a.querySelector("h3").textContent=x.name||"";a.querySelector("p").textContent=x.description||"";return a}))}
async function renderReviews(){try{const reviews=await (await fetch("/api/reviews")).json(),box=$("review-track");box.replaceChildren(...reviews.map(x=>{const a=document.createElement("article");a.className="review";a.innerHTML='<div class="stars"></div><h3></h3><p></p>';a.querySelector(".stars").textContent="★".repeat(x.rating)+"☆".repeat(5-x.rating);a.querySelector("h3").textContent=x.name;a.querySelector("p").textContent=x.text;return a}))}catch(e){}}
$("reviewForm").onsubmit=async e=>{e.preventDefault();const f=e.target,s=$("reviewStatus");try{const r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(f)))}),d=await r.json();if(!r.ok)throw Error(d.error);s.textContent=d.message||"Submitted for approval.";f.reset()}catch(x){s.textContent=x.message||"Could not submit review."}};
$("contactForm").onsubmit=async e=>{e.preventDefault();const f=e.target,s=$("form-status");try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(f)))});if(!r.ok)throw Error();s.textContent="Thanks — your inquiry has been received.";f.reset()}catch(x){s.textContent="Could not send right now."}};
function addMsg(text,type){const d=document.createElement("div");d.className="msg "+type;d.textContent=text;$("chatBody").appendChild(d);$("chatBody").scrollTop=$("chatBody").scrollHeight}
function setupChat(){const c=site.chatbot||{};$("chatName").textContent=c.name||"Style Assistant";addMsg(c.welcome||"Hi! How can I help?","bot");const q=$("quick");q.replaceChildren(...(c.quickReplies||[]).map(t=>{const b=document.createElement("button");b.textContent=t;b.onclick=()=>ask(t);return b}))}
async function ask(message){if(!message)return;addMsg(message,"user");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})}),d=await r.json();addMsg(d.reply||"Please contact our team.","bot")}catch(e){addMsg("Please contact our team directly.","bot")}}
$("chatForm").onsubmit=e=>{e.preventDefault();const i=$("chatInput"),m=i.value.trim();i.value="";ask(m)};$("chatFab").onclick=()=>$("chat").classList.toggle("open");$("chatClose").onclick=()=>$("chat").classList.remove("open");$("menuBtn").onclick=()=>$("navLinks").classList.toggle("open");loadSite();