const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname,DATA=path.join(ROOT,"data","site.json"),PORT=Number(process.env.PORT)||10000,HOST="0.0.0.0",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"",ADMIN_EMAIL=process.env.ADMIN_EMAIL||"admin@nexorafashion.local",sessions=new Map();
const MIME={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".svg":"image/svg+xml",".ico":"image/x-icon"};
if(!ADMIN_PASSWORD)console.warn("WARNING: ADMIN_PASSWORD is not set.");
const read=()=>JSON.parse(fs.readFileSync(DATA,"utf8")),write=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));
const txt=(v,n=5000)=>String(v??"").trim().slice(0,n);
function send(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,no)=>{let s="";req.on("data",c=>{s+=c;if(s.length>2000000)req.destroy()});req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on("error",no)})}
function token(req){return (req.headers.authorization||"").replace(/^Bearer\s+/i,"")}function isAdmin(req){return sessions.has(token(req))}
function orderId(d){let n=(d.orders||[]).length+1,id="NFX-"+String(n).padStart(6,"0");while(d.orders.some(x=>x.id===id)){n++;id="NFX-"+String(n).padStart(6,"0")}return id}
function makeReply(message,d){const q=txt(message,700),l=q.toLowerCase(),k=d.chatbot||{},bang=/[\u0980-\u09FF]/.test(q),orderWords=/order|অর্ডার|নিতে|নেব|নিন|buy|কিনবো|কিনতে/.test(l+" "+q),size=/size|sizing|সাইজ|মাপ|fit|ফিট/.test(l+" "+q),delivery=/delivery|shipping|ডেলিভারি|কুরিয়ার|courier/.test(l+" "+q),review=/review|রিভিউ|feedback|মতামত/.test(l+" "+q),category=/new|arrival|নতুন|women|মহিলা|নারী|men|পুরুষ|unisex|collection|কালেকশন/.test(l+" "+q);
 if(orderWords)return bang?"অবশ্যই ❤️ আমি order নিতে পারি। যে productটি নিতে চান তার নাম লিখুন বা product-এর “Order now” চাপুন। তারপর আপনার নাম, ফোন/WhatsApp, address ও payment method নেব।":"অবশ্যই ❤️ I can take your order. Tell me the product name or tap “Order now”; then I’ll collect your name, phone, address and payment method.";
 if(size)return bang?"অবশ্যই। Product-এর নাম ও আপনার usual size লিখুন—আমি available size দেখে বলব।":"Sure. Tell me the product and your usual size; I’ll check the available sizes.";
 if(delivery)return bang?"সারা বাংলাদেশে free delivery available—তবে final delivery details store policy অনুযায়ী admin panel থেকে manage করা যাবে।":"We offer free delivery across Bangladesh. Final delivery details are controlled from the store settings.";
 if(review)return bang?"Review দিতে Reviews section-এর “Write a review” button ব্যবহার করুন।":"Use the “Write a review” button in the Reviews section to submit feedback.";
 if(category){const names=(d.products||[]).slice(0,6).map(x=>x.name).join(", ");return bang?"অবশ্যই। আমাদের fashion collections-এ Women, Men, Unisex এবং New Arrivals আছে। কিছু available item: "+names:"Absolutely. We have Women, Men, Unisex and New Arrivals. Some available items: "+names}
 if(/hello|hi|hey|হাই|আসসালাম|salam/.test(l+" "+q))return k.welcome;
 return k.knowledge||"Tell me what fashion item, size or order help you need.";
}
async function api(req,res,u){
 if(req.method==="POST"&&u==="/api/login"){const b=await body(req);if(txt(b.email,180)!==ADMIN_EMAIL||txt(b.password,200)!==ADMIN_PASSWORD)return send(res,401,{error:"Invalid admin credentials"});const t=crypto.randomBytes(32).toString("hex");sessions.set(t,Date.now());return send(res,200,{token:t})}
 if(req.method==="POST"&&u==="/api/logout"){sessions.delete(token(req));return send(res,200,{ok:true})}
 if(req.method==="GET"&&u==="/api/site")return send(res,200,read());
 if(req.method==="POST"&&u==="/api/leads"){const b=await body(req);if(!b.name||!b.phone||!b.message)return send(res,400,{error:"Name, phone and message are required"});const d=read();d.leads=d.leads||[];d.leads.push({id:crypto.randomUUID(),type:"contact",name:txt(b.name,100),phone:txt(b.phone,40),email:txt(b.email,150),message:txt(b.message,3000),status:"new",createdAt:new Date().toISOString()});write(d);return send(res,201,{ok:true})}
 if(req.method==="POST"&&u==="/api/reviews"){const b=await body(req),rating=Math.max(1,Math.min(5,Number(b.rating)||5));if(!b.name||!b.text)return send(res,400,{error:"Name and review are required"});const d=read();d.reviews.push({id:crypto.randomUUID(),name:txt(b.name,100),rating,text:txt(b.text,1500),status:"pending",featured:false,createdAt:new Date().toISOString()});write(d);return send(res,201,{message:"Review submitted. It will appear after admin approval."})}
 if(req.method==="GET"&&u==="/api/reviews")return send(res,200,read().reviews.filter(x=>x.status==="approved"));
 if(req.method==="POST"&&u==="/api/orders"){const b=await body(req);if(!b.name||!b.phone||!b.address||!Array.isArray(b.items)||!b.items.length)return send(res,400,{error:"Order details are incomplete"});const d=read(),products=new Map(d.products.map(p=>[p.id,p]));const items=b.items.map(i=>{const p=products.get(i.productId);return p?{productId:p.id,name:p.name,price:p.price,quantity:Math.max(1,Math.min(20,Number(i.quantity)||1)),size:txt(i.size,20)}:null}).filter(Boolean);if(!items.length)return send(res,400,{error:"No valid products"});const total=items.reduce((s,i)=>s+i.price*i.quantity,0),o={id:orderId(d),name:txt(b.name,100),phone:txt(b.phone,40),address:txt(b.address,1000),payment:txt(b.payment,50),transactionId:txt(b.transactionId,100),items,total,status:"pending",source:txt(b.source,30)||"website",createdAt:new Date().toISOString()};d.orders.push(o);write(d);return send(res,201,{ok:true,order:o})}
 if(req.method==="POST"&&u==="/api/chat"){const b=await body(req),d=read();return send(res,200,{reply:makeReply(b.message,d),canOrder:true})}
 if(req.method==="PUT"&&u==="/api/site"){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});const b=await body(req),d=read();const n={...d,...b,settings:{...d.settings,...(b.settings||{})},hero:{...d.hero,...(b.hero||{})},chatbot:{...d.chatbot,...(b.chatbot||{})},socials:{...d.socials,...(b.socials||{})},orders:d.orders,leads:d.leads,reviews:Array.isArray(b.reviews)?b.reviews:d.reviews};write(n);return send(res,200,n)}
 if(req.method==="GET"&&u==="/api/admin/orders"){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});return send(res,200,read().orders)}
 if(req.method==="PATCH"&&u.startsWith("/api/admin/orders/")){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});const b=await body(req),d=read(),o=d.orders.find(x=>x.id===u.split("/").pop());if(!o)return send(res,404,{error:"Order not found"});o.status=txt(b.status,30)||o.status;write(d);return send(res,200,o)}
 if(req.method==="GET"&&u==="/api/admin/reviews"){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});return send(res,200,read().reviews)}
 if(req.method==="PATCH"&&u.startsWith("/api/admin/reviews/")){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});const b=await body(req),d=read(),r=d.reviews.find(x=>x.id===u.split("/").pop());if(!r)return send(res,404,{error:"Review not found"});if(b.status)r.status=txt(b.status,20);if(typeof b.featured==="boolean")r.featured=b.featured;write(d);return send(res,200,r)}
 if(req.method==="GET"&&u==="/api/admin/leads"){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});return send(res,200,read().leads)}
 if(req.method==="PATCH"&&u.startsWith("/api/admin/leads/")){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});const b=await body(req),d=read(),l=d.leads.find(x=>x.id===u.split("/").pop());if(!l)return send(res,404,{error:"Lead not found"});l.status=txt(b.status,30)||l.status;write(d);return send(res,200,l)}
 if(req.method==="GET"&&u==="/api/admin/stats"){if(!isAdmin(req))return send(res,401,{error:"Unauthorized"});const d=read();return send(res,200,{products:d.products.length,orders:d.orders.length,pendingOrders:d.orders.filter(x=>x.status==="pending").length,revenue:d.orders.filter(x=>x.status==="confirmed").reduce((s,x)=>s+x.total,0),reviews:d.reviews.length,pendingReviews:d.reviews.filter(x=>x.status==="pending").length,leads:d.leads.length})}
 return send(res,404,{error:"Not found"})
}
function staticFile(reqUrl){let rel=decodeURIComponent(reqUrl.split("?")[0]);if(rel==="/")rel="/index.html";if(rel==="/admin"||rel==="/admin/")rel="/admin.html";const f=path.resolve(ROOT,"."+rel);return f.startsWith(ROOT+path.sep)?f:null}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://localhost").pathname;if(u.startsWith("/api/"))return api(req,res,u);const f=staticFile(req.url);if(!f)return send(res,404,{error:"Not found"});fs.stat(f,(e,s)=>{if(e||!s.isFile())return send(res,404,{error:"Not found"});res.writeHead(200,{"Content-Type":MIME[path.extname(f).toLowerCase()]||"application/octet-stream","Cache-Control":"no-cache","X-Content-Type-Options":"nosniff"});fs.createReadStream(f).pipe(res)})}catch(e){console.error(e);send(res,500,{error:"Server error"})}});
server.listen(PORT,HOST,()=>console.log("NEXORA FASHION running on "+PORT+" | admin "+ADMIN_EMAIL));